"""empty message

Revision ID: 3532a1fe658d
Revises: 
Create Date: 2024-09-06 13:20:41.354601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3532a1fe658d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('userid', sa.String(length=10), nullable=False),
    sa.Column('usertype', sa.String(length=1), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank')
    # ### end Alembic commands ###
